create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.app_user_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  avatar_url text,
  home_country text,
  move_window text,
  planning_notes text,
  onboarding_complete boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.app_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('editor', 'admin', 'owner')),
  created_at timestamptz not null default now()
);

create or replace function public.is_admin_user()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.app_admins
    where user_id = auth.uid()
  );
$$;

create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  slug text not null,
  created_at timestamptz not null default now(),
  unique (user_id, slug)
);

create table if not exists public.retirement_dna_assessments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text,
  answers jsonb not null,
  profile jsonb not null,
  completion_percent integer not null default 0 check (completion_percent between 0 and 100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.saved_recommendation_sets (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  assessment_id uuid references public.retirement_dna_assessments(id) on delete set null,
  top_slugs text[] not null default '{}',
  summary jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.destinations_catalog (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  city text not null,
  country text not null,
  region text,
  latitude numeric(9, 6),
  longitude numeric(9, 6),
  tier text not null default 'launch',
  status text not null default 'draft' check (status in ('draft', 'review', 'published', 'archived')),
  hero_image_url text,
  description text,
  overview text,
  climate_summary text,
  lifestyle_summary text,
  healthcare_summary text,
  housing_summary text,
  cost_summary text,
  tax_summary text,
  visa_summary text,
  transportation_summary text,
  metadata jsonb not null default '{}'::jsonb,
  published_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.destination_tags (
  destination_id uuid not null references public.destinations_catalog(id) on delete cascade,
  tag text not null,
  created_at timestamptz not null default now(),
  primary key (destination_id, tag)
);

create table if not exists public.destination_media_assets (
  id uuid primary key default gen_random_uuid(),
  destination_id uuid not null references public.destinations_catalog(id) on delete cascade,
  kind text not null check (kind in ('hero', 'gallery', 'map', 'streetview', 'thumbnail')),
  provider text not null,
  url text not null,
  alt_text text,
  caption text,
  sort_order integer not null default 0,
  is_primary boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.destination_resource_links (
  id uuid primary key default gen_random_uuid(),
  destination_id uuid not null references public.destinations_catalog(id) on delete cascade,
  category text not null check (category in ('rentals', 'healthcare', 'taxes', 'visas', 'restaurants', 'guides', 'maps', 'government')),
  label text not null,
  provider text,
  url text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.destination_video_links (
  id uuid primary key default gen_random_uuid(),
  destination_id uuid not null references public.destinations_catalog(id) on delete cascade,
  provider text not null check (provider in ('youtube', 'tiktok', 'vimeo', 'custom')),
  label text not null,
  url text not null,
  embed_url text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.destination_content_revisions (
  id uuid primary key default gen_random_uuid(),
  destination_id uuid not null references public.destinations_catalog(id) on delete cascade,
  editor_user_id uuid references auth.users(id) on delete set null,
  change_summary text,
  payload jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_favorites_user_id on public.favorites(user_id);
create index if not exists idx_retirement_dna_assessments_user_id on public.retirement_dna_assessments(user_id, created_at desc);
create index if not exists idx_saved_recommendation_sets_user_id on public.saved_recommendation_sets(user_id, created_at desc);
create index if not exists idx_destinations_catalog_status on public.destinations_catalog(status, country, city);
create index if not exists idx_destination_tags_tag on public.destination_tags(tag);
create index if not exists idx_destination_media_assets_destination on public.destination_media_assets(destination_id, sort_order);
create index if not exists idx_destination_resource_links_destination on public.destination_resource_links(destination_id, category, sort_order);
create index if not exists idx_destination_video_links_destination on public.destination_video_links(destination_id, provider, sort_order);
create index if not exists idx_destination_content_revisions_destination on public.destination_content_revisions(destination_id, created_at desc);

drop trigger if exists set_updated_at_app_user_profiles on public.app_user_profiles;
create trigger set_updated_at_app_user_profiles
before update on public.app_user_profiles
for each row execute procedure public.set_updated_at();

drop trigger if exists set_updated_at_retirement_dna_assessments on public.retirement_dna_assessments;
create trigger set_updated_at_retirement_dna_assessments
before update on public.retirement_dna_assessments
for each row execute procedure public.set_updated_at();

drop trigger if exists set_updated_at_saved_recommendation_sets on public.saved_recommendation_sets;
create trigger set_updated_at_saved_recommendation_sets
before update on public.saved_recommendation_sets
for each row execute procedure public.set_updated_at();

drop trigger if exists set_updated_at_destinations_catalog on public.destinations_catalog;
create trigger set_updated_at_destinations_catalog
before update on public.destinations_catalog
for each row execute procedure public.set_updated_at();

drop trigger if exists set_updated_at_destination_media_assets on public.destination_media_assets;
create trigger set_updated_at_destination_media_assets
before update on public.destination_media_assets
for each row execute procedure public.set_updated_at();

drop trigger if exists set_updated_at_destination_resource_links on public.destination_resource_links;
create trigger set_updated_at_destination_resource_links
before update on public.destination_resource_links
for each row execute procedure public.set_updated_at();

drop trigger if exists set_updated_at_destination_video_links on public.destination_video_links;
create trigger set_updated_at_destination_video_links
before update on public.destination_video_links
for each row execute procedure public.set_updated_at();

alter table public.app_user_profiles enable row level security;
alter table public.app_admins enable row level security;
alter table public.favorites enable row level security;
alter table public.retirement_dna_assessments enable row level security;
alter table public.saved_recommendation_sets enable row level security;
alter table public.destinations_catalog enable row level security;
alter table public.destination_tags enable row level security;
alter table public.destination_media_assets enable row level security;
alter table public.destination_resource_links enable row level security;
alter table public.destination_video_links enable row level security;
alter table public.destination_content_revisions enable row level security;

drop policy if exists "Profiles selectable by owner or admin" on public.app_user_profiles;
create policy "Profiles selectable by owner or admin"
on public.app_user_profiles
for select
to authenticated
using (auth.uid() = user_id or public.is_admin_user());

drop policy if exists "Profiles insertable by owner" on public.app_user_profiles;
create policy "Profiles insertable by owner"
on public.app_user_profiles
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Profiles updatable by owner or admin" on public.app_user_profiles;
create policy "Profiles updatable by owner or admin"
on public.app_user_profiles
for update
to authenticated
using (auth.uid() = user_id or public.is_admin_user())
with check (auth.uid() = user_id or public.is_admin_user());

drop policy if exists "Admins can view admin roles" on public.app_admins;
create policy "Admins can view admin roles"
on public.app_admins
for select
to authenticated
using (auth.uid() = user_id or public.is_admin_user());

drop policy if exists "Admins can manage admin roles" on public.app_admins;
create policy "Admins can manage admin roles"
on public.app_admins
for all
to authenticated
using (public.is_admin_user())
with check (public.is_admin_user());

drop policy if exists "Users can read their own favorites" on public.favorites;
create policy "Users can read their own favorites"
on public.favorites
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can insert their own favorites" on public.favorites;
create policy "Users can insert their own favorites"
on public.favorites
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can delete their own favorites" on public.favorites;
create policy "Users can delete their own favorites"
on public.favorites
for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can read their own assessments" on public.retirement_dna_assessments;
create policy "Users can read their own assessments"
on public.retirement_dna_assessments
for select
to authenticated
using (auth.uid() = user_id or public.is_admin_user());

drop policy if exists "Users can insert their own assessments" on public.retirement_dna_assessments;
create policy "Users can insert their own assessments"
on public.retirement_dna_assessments
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update their own assessments" on public.retirement_dna_assessments;
create policy "Users can update their own assessments"
on public.retirement_dna_assessments
for update
to authenticated
using (auth.uid() = user_id or public.is_admin_user())
with check (auth.uid() = user_id or public.is_admin_user());

drop policy if exists "Users can read their own recommendation sets" on public.saved_recommendation_sets;
create policy "Users can read their own recommendation sets"
on public.saved_recommendation_sets
for select
to authenticated
using (auth.uid() = user_id or public.is_admin_user());

drop policy if exists "Users can insert their own recommendation sets" on public.saved_recommendation_sets;
create policy "Users can insert their own recommendation sets"
on public.saved_recommendation_sets
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update their own recommendation sets" on public.saved_recommendation_sets;
create policy "Users can update their own recommendation sets"
on public.saved_recommendation_sets
for update
to authenticated
using (auth.uid() = user_id or public.is_admin_user())
with check (auth.uid() = user_id or public.is_admin_user());

drop policy if exists "Published destinations are viewable" on public.destinations_catalog;
create policy "Published destinations are viewable"
on public.destinations_catalog
for select
to anon, authenticated
using (status = 'published' or public.is_admin_user());

drop policy if exists "Admins manage destinations" on public.destinations_catalog;
create policy "Admins manage destinations"
on public.destinations_catalog
for all
to authenticated
using (public.is_admin_user())
with check (public.is_admin_user());

drop policy if exists "Published destination tags are viewable" on public.destination_tags;
create policy "Published destination tags are viewable"
on public.destination_tags
for select
to anon, authenticated
using (
  exists (
    select 1
    from public.destinations_catalog
    where id = destination_id
      and (status = 'published' or public.is_admin_user())
  )
);

drop policy if exists "Admins manage destination tags" on public.destination_tags;
create policy "Admins manage destination tags"
on public.destination_tags
for all
to authenticated
using (public.is_admin_user())
with check (public.is_admin_user());

drop policy if exists "Published media is viewable" on public.destination_media_assets;
create policy "Published media is viewable"
on public.destination_media_assets
for select
to anon, authenticated
using (
  exists (
    select 1
    from public.destinations_catalog
    where id = destination_id
      and (status = 'published' or public.is_admin_user())
  )
);

drop policy if exists "Admins manage media" on public.destination_media_assets;
create policy "Admins manage media"
on public.destination_media_assets
for all
to authenticated
using (public.is_admin_user())
with check (public.is_admin_user());

drop policy if exists "Published resources are viewable" on public.destination_resource_links;
create policy "Published resources are viewable"
on public.destination_resource_links
for select
to anon, authenticated
using (
  exists (
    select 1
    from public.destinations_catalog
    where id = destination_id
      and (status = 'published' or public.is_admin_user())
  )
);

drop policy if exists "Admins manage resources" on public.destination_resource_links;
create policy "Admins manage resources"
on public.destination_resource_links
for all
to authenticated
using (public.is_admin_user())
with check (public.is_admin_user());

drop policy if exists "Published videos are viewable" on public.destination_video_links;
create policy "Published videos are viewable"
on public.destination_video_links
for select
to anon, authenticated
using (
  exists (
    select 1
    from public.destinations_catalog
    where id = destination_id
      and (status = 'published' or public.is_admin_user())
  )
);

drop policy if exists "Admins manage videos" on public.destination_video_links;
create policy "Admins manage videos"
on public.destination_video_links
for all
to authenticated
using (public.is_admin_user())
with check (public.is_admin_user());

drop policy if exists "Admins view revisions" on public.destination_content_revisions;
create policy "Admins view revisions"
on public.destination_content_revisions
for select
to authenticated
using (public.is_admin_user());

drop policy if exists "Admins create revisions" on public.destination_content_revisions;
create policy "Admins create revisions"
on public.destination_content_revisions
for insert
to authenticated
with check (public.is_admin_user());