import type { CategoryDefinition, DataCategoryKey } from "./types";

type Seed = Omit<CategoryDefinition, "key">;

const commonVerification =
  "Automated schema checks, anomaly thresholds, source cross-check, and admin approval before publish.";

const category = (key: DataCategoryKey, seed: Seed): CategoryDefinition => ({ key, ...seed });

export const DATA_CATEGORY_CATALOG: Record<DataCategoryKey, CategoryDefinition> = {
  monthly_weather: category("monthly_weather", {
    label: "Monthly Weather (12 months)",
    primarySource: "Open-Meteo Climate API",
    backupSource: "Meteostat monthly normals",
    licensing: "Open-Meteo attribution required; verify Meteostat terms for redistribution.",
    updateFrequency: "Monthly refresh; annual baseline recompute.",
    confidenceRule: "High when both sources agree within configured tolerance.",
    verificationProcess: commonVerification,
    schemaTarget: "monthly_climate",
    importStrategy: "API pull by lat/lon; normalize to month_index/month_name.",
    refreshStrategy: "Scheduled monthly jobs with yearly backfill check.",
  }),
  climate_averages: category("climate_averages", {
    label: "Climate Averages",
    primarySource: "Open-Meteo Climate API",
    backupSource: "NOAA/ECMWF aggregates via approved provider",
    licensing: "Provider attribution and non-restricted downstream usage review.",
    updateFrequency: "Quarterly",
    confidenceRule: "High after seasonal deltas pass quality gates.",
    verificationProcess: commonVerification,
    schemaTarget: "destination_core_metrics",
    importStrategy: "Derived metrics from monthly climate feed.",
    refreshStrategy: "Quarterly recomputation job.",
  }),
  rainfall: category("rainfall", {
    label: "Rainfall",
    primarySource: "Open-Meteo",
    backupSource: "Meteostat",
    licensing: "Attribution and cache policy compliance.",
    updateFrequency: "Monthly",
    confidenceRule: "High with <10% variance between sources.",
    verificationProcess: commonVerification,
    schemaTarget: "monthly_climate",
    importStrategy: "Stored as rainfall_mm per month.",
    refreshStrategy: "Monthly scheduled refresh.",
  }),
  humidity: category("humidity", {
    label: "Humidity",
    primarySource: "Open-Meteo",
    backupSource: "Meteostat",
    licensing: "Attribution required.",
    updateFrequency: "Monthly",
    confidenceRule: "Medium unless dual-source agreement threshold met.",
    verificationProcess: commonVerification,
    schemaTarget: "monthly_climate",
    importStrategy: "Store humidity_pct by month.",
    refreshStrategy: "Monthly refresh.",
  }),
  sunshine_hours: category("sunshine_hours", {
    label: "Sunshine Hours",
    primarySource: "Open-Meteo",
    backupSource: "Meteostat",
    licensing: "Attribution required.",
    updateFrequency: "Monthly",
    confidenceRule: "High if anomaly checks pass.",
    verificationProcess: commonVerification,
    schemaTarget: "monthly_climate",
    importStrategy: "Store sunshine_hours per month.",
    refreshStrategy: "Monthly refresh.",
  }),
  uv_index: category("uv_index", {
    label: "UV Index",
    primarySource: "Open-Meteo",
    backupSource: "OpenUV or equivalent licensed provider",
    licensing: "Provider-specific API license review.",
    updateFrequency: "Monthly",
    confidenceRule: "Medium by default; high with corroborating source.",
    verificationProcess: commonVerification,
    schemaTarget: "monthly_climate",
    importStrategy: "Store uv_index monthly.",
    refreshStrategy: "Monthly refresh.",
  }),
  sea_temperature: category("sea_temperature", {
    label: "Sea Temperature",
    primarySource: "Open-Meteo Marine",
    backupSource: "Copernicus Marine datasets",
    licensing: "Marine dataset redistribution terms review.",
    updateFrequency: "Monthly",
    confidenceRule: "High for coastal destinations with source agreement.",
    verificationProcess: commonVerification,
    schemaTarget: "monthly_climate",
    importStrategy: "Store sea_temp_c where applicable.",
    refreshStrategy: "Monthly coastal-only refresh jobs.",
  }),
  air_quality: category("air_quality", {
    label: "Air Quality",
    primarySource: "OpenAQ / WAQI licensed feed",
    backupSource: "IQAir historical datasets",
    licensing: "Strictly enforce API redistribution/license terms.",
    updateFrequency: "Weekly",
    confidenceRule: "High only with recent station coverage.",
    verificationProcess: commonVerification,
    schemaTarget: "safety_metrics",
    importStrategy: "Aggregate PM2.5/PM10/NO2 into metrics.",
    refreshStrategy: "Weekly rolling-window updates.",
  }),
  cost_of_living: category("cost_of_living", {
    label: "Cost of Living",
    primarySource: "Numbeo API or licensed equivalent",
    backupSource: "National statistics portals",
    licensing: "Commercial usage and redistribution must be licensed.",
    updateFrequency: "Monthly",
    confidenceRule: "Medium baseline; high when validated against national data.",
    verificationProcess: commonVerification,
    schemaTarget: "cost_of_living_items",
    importStrategy: "Normalize to metric keys and display values.",
    refreshStrategy: "Monthly source sync with drift checks.",
  }),
  grocery_prices: category("grocery_prices", {
    label: "Grocery Prices",
    primarySource: "Numbeo licensed feed",
    backupSource: "National CPI food basket datasets",
    licensing: "License required for scaled redistribution.",
    updateFrequency: "Monthly",
    confidenceRule: "High if source spread within threshold.",
    verificationProcess: commonVerification,
    schemaTarget: "cost_of_living_items",
    importStrategy: "Store per-item price metrics.",
    refreshStrategy: "Monthly sync.",
  }),
  restaurant_prices: category("restaurant_prices", {
    label: "Restaurant Prices",
    primarySource: "Numbeo licensed feed",
    backupSource: "National tourism/statistics feeds",
    licensing: "License and attribution checks.",
    updateFrequency: "Monthly",
    confidenceRule: "Medium to high based on source age and consistency.",
    verificationProcess: commonVerification,
    schemaTarget: "cost_of_living_items",
    importStrategy: "Store standardized restaurant basket metrics.",
    refreshStrategy: "Monthly sync.",
  }),
  utility_costs: category("utility_costs", {
    label: "Utility Costs",
    primarySource: "Numbeo licensed feed",
    backupSource: "Local utility regulator datasets",
    licensing: "Utility data reuse terms vary by country.",
    updateFrequency: "Monthly",
    confidenceRule: "High if regulator values present.",
    verificationProcess: commonVerification,
    schemaTarget: "cost_of_living_items",
    importStrategy: "Store composite and component utility costs.",
    refreshStrategy: "Monthly with quarterly regulator reconciliation.",
  }),
  fuel_prices: category("fuel_prices", {
    label: "Fuel Prices",
    primarySource: "GlobalPetrolPrices API",
    backupSource: "Government energy portals",
    licensing: "Commercial API license required.",
    updateFrequency: "Weekly",
    confidenceRule: "High with government reconciliation.",
    verificationProcess: commonVerification,
    schemaTarget: "cost_of_living_items",
    importStrategy: "Normalize to per-liter fuel metrics.",
    refreshStrategy: "Weekly updates.",
  }),
  rent_prices: category("rent_prices", {
    label: "Rent Prices",
    primarySource: "Housing data partner API",
    backupSource: "National housing registries",
    licensing: "Depends on partner agreements and MLS terms.",
    updateFrequency: "Weekly",
    confidenceRule: "High when sample size thresholds are met.",
    verificationProcess: commonVerification,
    schemaTarget: "housing_market_metrics",
    importStrategy: "Normalize by apartment size and location class.",
    refreshStrategy: "Weekly rolling median refresh.",
  }),
  home_purchase_prices: category("home_purchase_prices", {
    label: "Home Purchase Prices",
    primarySource: "Housing data partner API",
    backupSource: "Government transaction registries",
    licensing: "Partner/government re-use terms apply.",
    updateFrequency: "Monthly",
    confidenceRule: "High with transaction-backed data.",
    verificationProcess: commonVerification,
    schemaTarget: "housing_market_metrics",
    importStrategy: "Normalize to price-per-sqm and medians.",
    refreshStrategy: "Monthly refresh and outlier pruning.",
  }),
  property_taxes: category("property_taxes", {
    label: "Property Taxes",
    primarySource: "Official tax authority portals",
    backupSource: "PwC and OECD tax summaries",
    licensing: "Official sources preferred; summary sources require attribution.",
    updateFrequency: "Quarterly",
    confidenceRule: "High with official statute references.",
    verificationProcess: commonVerification,
    schemaTarget: "tax_rules",
    importStrategy: "Extract jurisdiction, rates, exemptions.",
    refreshStrategy: "Quarterly legal review jobs.",
  }),
  healthcare: category("healthcare", {
    label: "Healthcare Overview",
    primarySource: "Government health ministry datasets",
    backupSource: "WHO/OECD health indicators",
    licensing: "Public data with attribution; verify downstream terms.",
    updateFrequency: "Quarterly",
    confidenceRule: "High with ministry source and current timestamp.",
    verificationProcess: commonVerification,
    schemaTarget: "healthcare_services",
    importStrategy: "Normalize macro healthcare service indicators.",
    refreshStrategy: "Quarterly refresh.",
  }),
  hospitals: category("hospitals", {
    label: "Hospitals",
    primarySource: "OpenStreetMap + official facility registers",
    backupSource: "Google Places licensed feed",
    licensing: "OSM ODbL obligations; Places API terms if used.",
    updateFrequency: "Monthly",
    confidenceRule: "High when facility appears in official registry.",
    verificationProcess: commonVerification,
    schemaTarget: "healthcare_facilities",
    importStrategy: "Entity ingestion with name, category, location, notes.",
    refreshStrategy: "Monthly sync + duplicate merge.",
  }),
  clinics: category("clinics", {
    label: "Clinics",
    primarySource: "OpenStreetMap + health registers",
    backupSource: "Google Places licensed feed",
    licensing: "OSM ODbL and API TOS compliance.",
    updateFrequency: "Monthly",
    confidenceRule: "Medium baseline, high with official corroboration.",
    verificationProcess: commonVerification,
    schemaTarget: "healthcare_facilities",
    importStrategy: "POI ingestion filtered to clinic entities.",
    refreshStrategy: "Monthly sync.",
  }),
  specialists: category("specialists", {
    label: "Specialists",
    primarySource: "National provider directories",
    backupSource: "Hospital and insurer directories",
    licensing: "Directory scraping/use restrictions must be respected.",
    updateFrequency: "Quarterly",
    confidenceRule: "High with official registry IDs.",
    verificationProcess: commonVerification,
    schemaTarget: "healthcare_services",
    importStrategy: "Normalize by specialty and availability.",
    refreshStrategy: "Quarterly provider reconciliation.",
  }),
  pharmacies: category("pharmacies", {
    label: "Pharmacies",
    primarySource: "OpenStreetMap + regulator registries",
    backupSource: "Google Places licensed feed",
    licensing: "OSM and provider terms compliance.",
    updateFrequency: "Monthly",
    confidenceRule: "High with regulator match.",
    verificationProcess: commonVerification,
    schemaTarget: "healthcare_facilities",
    importStrategy: "POI ingestion with type=pharmacy.",
    refreshStrategy: "Monthly sync.",
  }),
  airports: category("airports", {
    label: "Airports",
    primarySource: "OurAirports/OpenFlights + official airport APIs",
    backupSource: "IATA datasets (licensed)",
    licensing: "IATA and airport feed licensing varies.",
    updateFrequency: "Monthly",
    confidenceRule: "High with official airport authority confirmation.",
    verificationProcess: commonVerification,
    schemaTarget: "airports",
    importStrategy: "Normalize airport entities with IATA/ICAO and distance.",
    refreshStrategy: "Monthly sync.",
  }),
  airlines: category("airlines", {
    label: "Airlines",
    primarySource: "Official airport route datasets",
    backupSource: "OpenFlights or licensed route providers",
    licensing: "Route data redistribution rights required.",
    updateFrequency: "Monthly",
    confidenceRule: "Medium unless authority feed available.",
    verificationProcess: commonVerification,
    schemaTarget: "transportation_options",
    importStrategy: "Map carriers/routes to transportation options.",
    refreshStrategy: "Monthly route refresh.",
  }),
  airport_drive_times: category("airport_drive_times", {
    label: "Airport Drive Times",
    primarySource: "Google Distance Matrix API",
    backupSource: "OpenRouteService/Mapbox routing",
    licensing: "Routing API terms and caching limits apply.",
    updateFrequency: "Weekly",
    confidenceRule: "High for fresh route computations.",
    verificationProcess: commonVerification,
    schemaTarget: "airports",
    importStrategy: "Compute drive time from city centroid to airport.",
    refreshStrategy: "Weekly route recomputation.",
  }),
  transportation: category("transportation", {
    label: "Transportation",
    primarySource: "GTFS transit feeds and municipal open data",
    backupSource: "Moovit/OpenTrip planner licensed data",
    licensing: "GTFS license varies by agency.",
    updateFrequency: "Monthly",
    confidenceRule: "High with official GTFS updates.",
    verificationProcess: commonVerification,
    schemaTarget: "transportation_options",
    importStrategy: "Normalize transit modes and service indicators.",
    refreshStrategy: "Monthly refresh.",
  }),
  walkability: category("walkability", {
    label: "Walkability",
    primarySource: "OpenStreetMap derived walkability model",
    backupSource: "Mapbox accessibility metrics",
    licensing: "OSM ODbL and model attribution.",
    updateFrequency: "Quarterly",
    confidenceRule: "Medium until calibrated by local validation.",
    verificationProcess: commonVerification,
    schemaTarget: "destination_core_metrics",
    importStrategy: "Compute walkability index from street-network features.",
    refreshStrategy: "Quarterly recompute.",
  }),
  internet_speeds: category("internet_speeds", {
    label: "Internet Speeds",
    primarySource: "Ookla or M-Lab licensed datasets",
    backupSource: "National telecom regulators",
    licensing: "Commercial speed datasets require explicit license.",
    updateFrequency: "Monthly",
    confidenceRule: "High when sample size threshold is met.",
    verificationProcess: commonVerification,
    schemaTarget: "internet_metrics",
    importStrategy: "Normalize median download/upload/latency metrics.",
    refreshStrategy: "Monthly refresh.",
  }),
  mobile_coverage: category("mobile_coverage", {
    label: "Mobile Coverage",
    primarySource: "OpenSignal licensed feeds",
    backupSource: "Regulator coverage maps",
    licensing: "Coverage datasets usually restricted; enforce contracts.",
    updateFrequency: "Quarterly",
    confidenceRule: "Medium baseline; high with regulator overlays.",
    verificationProcess: commonVerification,
    schemaTarget: "internet_metrics",
    importStrategy: "Coverage tier and operator quality metrics.",
    refreshStrategy: "Quarterly refresh.",
  }),
  schools: category("schools", {
    label: "Schools",
    primarySource: "Government education directories",
    backupSource: "OpenStreetMap + curated school listings",
    licensing: "Public directory terms vary; confirm reuse.",
    updateFrequency: "Quarterly",
    confidenceRule: "High with official IDs and active status.",
    verificationProcess: commonVerification,
    schemaTarget: "schools",
    importStrategy: "Entity ingestion with level and type tags.",
    refreshStrategy: "Quarterly sync.",
  }),
  international_schools: category("international_schools", {
    label: "International Schools",
    primarySource: "International school association directories",
    backupSource: "Education ministry + school websites",
    licensing: "Directory license and scraping restrictions apply.",
    updateFrequency: "Quarterly",
    confidenceRule: "High when accreditation is confirmed.",
    verificationProcess: commonVerification,
    schemaTarget: "schools",
    importStrategy: "Filter and tag schools by curriculum/accreditation.",
    refreshStrategy: "Quarterly refresh.",
  }),
  universities: category("universities", {
    label: "Universities",
    primarySource: "Government higher-ed registries",
    backupSource: "OpenAlex/Wikidata cross-reference",
    licensing: "Open datasets with attribution requirements.",
    updateFrequency: "Quarterly",
    confidenceRule: "High with official accreditation mapping.",
    verificationProcess: commonVerification,
    schemaTarget: "schools",
    importStrategy: "Ingest tertiary institutions into education entities.",
    refreshStrategy: "Quarterly refresh.",
  }),
  golf_courses: category("golf_courses", {
    label: "Golf Courses",
    primarySource: "OpenStreetMap + official course directories",
    backupSource: "Google Places licensed feed",
    licensing: "OSM ODbL and API TOS.",
    updateFrequency: "Monthly",
    confidenceRule: "High with official site confirmation.",
    verificationProcess: commonVerification,
    schemaTarget: "golf_courses",
    importStrategy: "POI ingestion and enrichment.",
    refreshStrategy: "Monthly refresh.",
  }),
  pickleball: category("pickleball", {
    label: "Pickleball",
    primarySource: "OpenStreetMap sport tags + local directories",
    backupSource: "Google Places licensed feed",
    licensing: "OSM ODbL and partner terms.",
    updateFrequency: "Monthly",
    confidenceRule: "Medium unless source authority is available.",
    verificationProcess: commonVerification,
    schemaTarget: "recreation_facilities",
    importStrategy: "POI ingestion by sport type.",
    refreshStrategy: "Monthly refresh.",
  }),
  tennis: category("tennis", {
    label: "Tennis",
    primarySource: "OpenStreetMap sport tags",
    backupSource: "Local sports authority datasets",
    licensing: "OSM ODbL and local data terms.",
    updateFrequency: "Monthly",
    confidenceRule: "Medium to high depending on source.",
    verificationProcess: commonVerification,
    schemaTarget: "recreation_facilities",
    importStrategy: "POI ingestion by sport type.",
    refreshStrategy: "Monthly refresh.",
  }),
  beaches: category("beaches", {
    label: "Beaches",
    primarySource: "OpenStreetMap coastline POIs",
    backupSource: "Blue Flag beach datasets",
    licensing: "OSM ODbL and dataset-specific terms.",
    updateFrequency: "Monthly",
    confidenceRule: "High with official beach certifications.",
    verificationProcess: commonVerification,
    schemaTarget: "beaches",
    importStrategy: "Entity ingestion with amenities flags.",
    refreshStrategy: "Monthly refresh.",
  }),
  hiking: category("hiking", {
    label: "Hiking",
    primarySource: "OpenStreetMap trails",
    backupSource: "AllTrails licensed data",
    licensing: "Trail data licensing constraints apply.",
    updateFrequency: "Quarterly",
    confidenceRule: "Medium baseline.",
    verificationProcess: commonVerification,
    schemaTarget: "recreation_facilities",
    importStrategy: "Trail network aggregation into recreation entities.",
    refreshStrategy: "Quarterly refresh.",
  }),
  parks: category("parks", {
    label: "Parks",
    primarySource: "OpenStreetMap",
    backupSource: "Municipal GIS datasets",
    licensing: "OSM ODbL and municipal licensing.",
    updateFrequency: "Quarterly",
    confidenceRule: "High with municipal GIS corroboration.",
    verificationProcess: commonVerification,
    schemaTarget: "recreation_facilities",
    importStrategy: "POI and polygon extraction.",
    refreshStrategy: "Quarterly refresh.",
  }),
  museums: category("museums", {
    label: "Museums",
    primarySource: "OpenStreetMap cultural POIs",
    backupSource: "Official tourism boards",
    licensing: "OSM and tourism board terms.",
    updateFrequency: "Quarterly",
    confidenceRule: "Medium to high by source quality.",
    verificationProcess: commonVerification,
    schemaTarget: "recreation_facilities",
    importStrategy: "Cultural POI ingestion.",
    refreshStrategy: "Quarterly refresh.",
  }),
  restaurants: category("restaurants", {
    label: "Restaurants",
    primarySource: "OpenStreetMap + licensed POI partners",
    backupSource: "Google Places licensed feed",
    licensing: "POI provider terms and ODbL obligations.",
    updateFrequency: "Monthly",
    confidenceRule: "High for counts with cross-source agreement.",
    verificationProcess: commonVerification,
    schemaTarget: "restaurants_or_food_metrics",
    importStrategy: "Count and density metrics plus key entities.",
    refreshStrategy: "Monthly refresh.",
  }),
  coffee_shops: category("coffee_shops", {
    label: "Coffee Shops",
    primarySource: "OpenStreetMap amenity=cafe",
    backupSource: "Licensed POI provider",
    licensing: "ODbL and provider terms.",
    updateFrequency: "Monthly",
    confidenceRule: "Medium baseline; high with multi-source counts.",
    verificationProcess: commonVerification,
    schemaTarget: "restaurants_or_food_metrics",
    importStrategy: "Cafe density metrics and featured entities.",
    refreshStrategy: "Monthly refresh.",
  }),
  nightlife: category("nightlife", {
    label: "Nightlife",
    primarySource: "OpenStreetMap nightlife POIs",
    backupSource: "Licensed POI partner",
    licensing: "ODbL and provider terms.",
    updateFrequency: "Monthly",
    confidenceRule: "Medium by default.",
    verificationProcess: commonVerification,
    schemaTarget: "restaurants_or_food_metrics",
    importStrategy: "POI counts and density metrics.",
    refreshStrategy: "Monthly refresh.",
  }),
  crime_safety: category("crime_safety", {
    label: "Crime and Safety",
    primarySource: "Official police/open crime datasets",
    backupSource: "Numbeo (licensed) and safety advisories",
    licensing: "Jurisdiction-specific crime data terms.",
    updateFrequency: "Monthly",
    confidenceRule: "High only with official crime feeds.",
    verificationProcess: commonVerification,
    schemaTarget: "safety_metrics",
    importStrategy: "Normalize crime rates and safety indicators.",
    refreshStrategy: "Monthly refresh with trend deltas.",
  }),
  visa_options: category("visa_options", {
    label: "Visa Options",
    primarySource: "Official immigration portals",
    backupSource: "EU Immigration Portal / consular portals",
    licensing: "Public legal text; ensure citation and timestamp.",
    updateFrequency: "Monthly",
    confidenceRule: "High with official legal references.",
    verificationProcess: commonVerification,
    schemaTarget: "visa_programs",
    importStrategy: "Policy extraction into structured visa rules.",
    refreshStrategy: "Monthly legal source crawl and diff.",
  }),
  residency: category("residency", {
    label: "Residency",
    primarySource: "Official immigration portals",
    backupSource: "Consular guidance docs",
    licensing: "Public policy terms with attribution.",
    updateFrequency: "Monthly",
    confidenceRule: "High with official decree references.",
    verificationProcess: commonVerification,
    schemaTarget: "visa_programs",
    importStrategy: "Residency pathway normalization.",
    refreshStrategy: "Monthly policy checks.",
  }),
  tax_information: category("tax_information", {
    label: "Tax Information",
    primarySource: "Official tax authorities",
    backupSource: "PwC/OECD summaries",
    licensing: "Official/public sources preferred; attribution required.",
    updateFrequency: "Quarterly",
    confidenceRule: "High with official statute links.",
    verificationProcess: commonVerification,
    schemaTarget: "tax_rules",
    importStrategy: "Normalize tax rules and brackets.",
    refreshStrategy: "Quarterly legal refresh.",
  }),
  population: category("population", {
    label: "Population",
    primarySource: "National statistics offices",
    backupSource: "World Bank/UN datasets",
    licensing: "Open statistical usage with citation.",
    updateFrequency: "Quarterly",
    confidenceRule: "High when year and authority are explicit.",
    verificationProcess: commonVerification,
    schemaTarget: "destination_core_metrics",
    importStrategy: "Normalize total population and growth metrics.",
    refreshStrategy: "Quarterly refresh.",
  }),
  language: category("language", {
    label: "Language",
    primarySource: "Government and census datasets",
    backupSource: "Ethnologue/Wikidata cross-reference",
    licensing: "Check rights for language distribution datasets.",
    updateFrequency: "Yearly",
    confidenceRule: "High with census references.",
    verificationProcess: commonVerification,
    schemaTarget: "destination_core_metrics",
    importStrategy: "Store primary/secondary language metrics.",
    refreshStrategy: "Annual refresh.",
  }),
  currency: category("currency", {
    label: "Currency",
    primarySource: "ISO 4217 and central bank datasets",
    backupSource: "IMF/World Bank metadata",
    licensing: "Open metadata with attribution.",
    updateFrequency: "Yearly",
    confidenceRule: "High with ISO code validation.",
    verificationProcess: commonVerification,
    schemaTarget: "destination_core_metrics",
    importStrategy: "Store currency code and symbol fields.",
    refreshStrategy: "Annual refresh.",
  }),
  time_zone: category("time_zone", {
    label: "Time Zone",
    primarySource: "IANA tz database",
    backupSource: "GeoNames timezone API",
    licensing: "IANA open use terms.",
    updateFrequency: "Monthly",
    confidenceRule: "High with tz database match.",
    verificationProcess: commonVerification,
    schemaTarget: "destination_core_metrics",
    importStrategy: "Geo lookup to canonical tz id.",
    refreshStrategy: "Monthly tz database sync.",
  }),
  emergency_numbers: category("emergency_numbers", {
    label: "Emergency Numbers",
    primarySource: "Official government portals",
    backupSource: "Travel.state.gov and embassy advisories",
    licensing: "Public government guidance with citation.",
    updateFrequency: "Quarterly",
    confidenceRule: "High with official source timestamp.",
    verificationProcess: commonVerification,
    schemaTarget: "destination_resources",
    importStrategy: "Structured contact resource records.",
    refreshStrategy: "Quarterly checks.",
  }),
  local_government: category("local_government", {
    label: "Local Government",
    primarySource: "Municipal official websites",
    backupSource: "National municipal registries",
    licensing: "Public URLs and metadata only.",
    updateFrequency: "Quarterly",
    confidenceRule: "High when domain ownership is official.",
    verificationProcess: commonVerification,
    schemaTarget: "destination_resources",
    importStrategy: "Official contact and portal links.",
    refreshStrategy: "Quarterly link validation.",
  }),
  tourism: category("tourism", {
    label: "Tourism",
    primarySource: "Official tourism boards",
    backupSource: "UNWTO or national tourism stats",
    licensing: "Use licensed/open tourism indicators.",
    updateFrequency: "Quarterly",
    confidenceRule: "Medium to high by source authority.",
    verificationProcess: commonVerification,
    schemaTarget: "destination_resources",
    importStrategy: "Tourism resources and indicators ingestion.",
    refreshStrategy: "Quarterly refresh.",
  }),
  google_maps_links: category("google_maps_links", {
    label: "Google Maps Links",
    primarySource: "Deterministic generated URLs",
    backupSource: "N/A",
    licensing: "Comply with Google Maps Platform terms where required.",
    updateFrequency: "On destination create/update",
    confidenceRule: "High for generated deterministic links.",
    verificationProcess: "URL validity checks and periodic 200/redirect checks.",
    schemaTarget: "destination_resources",
    importStrategy: "Generate by city/country and key POI coordinates.",
    refreshStrategy: "Regenerate when geodata changes.",
  }),
  youtube_links: category("youtube_links", {
    label: "YouTube Links",
    primarySource: "YouTube Data API v3",
    backupSource: "Manual curation queue",
    licensing: "YouTube API usage and display terms.",
    updateFrequency: "Monthly",
    confidenceRule: "Medium unless manually approved.",
    verificationProcess: "API fetch + admin content suitability approval.",
    schemaTarget: "destination_video_links",
    importStrategy: "Query and stage candidates for approval.",
    refreshStrategy: "Monthly refresh and stale link pruning.",
  }),
  rental_resources: category("rental_resources", {
    label: "Rental Resources",
    primarySource: "Trusted rental portals (licensed)",
    backupSource: "Government housing portals",
    licensing: "Portal terms may restrict automated reuse.",
    updateFrequency: "Monthly",
    confidenceRule: "High for official/government links.",
    verificationProcess: "Link integrity and domain trust checks + admin approval.",
    schemaTarget: "destination_resource_links",
    importStrategy: "Curated source-link ingestion.",
    refreshStrategy: "Monthly link health checks.",
  }),
  real_estate_resources: category("real_estate_resources", {
    label: "Real Estate Resources",
    primarySource: "Trusted real estate portals (licensed)",
    backupSource: "Municipal registries and associations",
    licensing: "MLS/portal redistribution restrictions apply.",
    updateFrequency: "Monthly",
    confidenceRule: "High when portal is authoritative and active.",
    verificationProcess: "Domain trust, link checks, and admin approval.",
    schemaTarget: "destination_resource_links",
    importStrategy: "Source-link ingestion with category tagging.",
    refreshStrategy: "Monthly link and ownership checks.",
  }),
};

export const DATA_CATEGORY_ROADMAP: DataCategoryKey[] = [
  "monthly_weather",
  "cost_of_living",
  "rent_prices",
  "home_purchase_prices",
  "hospitals",
  "airports",
  "airport_drive_times",
  "internet_speeds",
  "crime_safety",
  "visa_options",
  "tax_information",
  "schools",
  "beaches",
  "golf_courses",
  "restaurants",
  "transportation",
];
